home_page: home.md # filename under /source/_posts/
menu_page: menu.md # filename under /source/_posts/

favicon_url: favicon.ico
google_analytics: # UA-XXXXX-Y

comments:
  utterances:
    enable: false
    user: # your github user name
    repo: # your github repo name
  disqus:
    enable: false
    shortname: # your disqus shortname
  gitalk:
    enable: false
    githubID: # your github id
    repo: # GitHub repository e.g. kaiiiz.github.io
    ClientID: # GitHub Application Client ID
    ClientSecret: # GitHub Application Client Secret
    adminUser: # GitHub repository owner and collaborators
    labels: 'gitalk' # GitHub issue labels
    distractionFreeMode: true
